config/routes.rb
Rails.application.routes.draw do

  root to: 'home#top'
  get '/home/about' => 'home#about'

  devise_for :users

  resources :books, except: [:new] do
  	resource :favorites, only: [:create, :destroy]
    resource :book_comments, only: [:create]
   end
    resources :book_comments, only: [:destroy]
  resources :users, only: [:index, :show, :edit, :update, :destroy]  do
    member do
     get :following, :followers
    end
  end

post 'follow/:id' => 'relationships#follow', as: 'follow' # フォローする
post 'unfollow/:id' => 'relationships#unfollow', as: 'unfollow' # フォロー外す
 
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord

	validates :title, presence: true
    validates :body, presence: true, length: { maximum: 200 }

    belongs_to :user
    has_many :book_comments, dependent: :destroy
	has_many :favorites, dependent: :destroy
     def favorited_by?(user)
            favorites.where(user_id: user.id).exists?
        end
end

app/models/book_comment.rb
class BookComment < ApplicationRecord
	belongs_to :book
	belongs_to :user

	validates :comment, presence: true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
	belongs_to :book
	belongs_to :user
end

app/models/relationship.rb
class Relationship < ApplicationRecord
	belongs_to :follower, class_name: "User"
    belongs_to :following, class_name: "User"
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books,dependent: :destroy
  has_many :book_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  attachment :profile_image

  validates :name, presence: true, length: { in: 2..20 }
  validates :introduction, length: { maximum: 50 }

  has_many :follower, class_name: "Relationship",
                     foreign_key: "follower_id",
                         dependent: :destroy # フォロー取得
  has_many :following, class_name: "Relationship",
                     foreign_key: "following_id",
                       dependent: :destroy # フォロワー取得
  has_many :following_user, through: :follower, source: :following # 自分がフォローしている人
  has_many :follower_user, through: :following, source: :follower # 自分をフォローしている人

  # ユーザーをフォローする
  def follow(user_id)
    following.create( follower_id: user_id)
  end

  # ユーザーのフォローを外す
  def unfollow(user_id)
    following.find_by( follower_id: user_id).destroy
  end

  # フォローしていればtrueを返す
  def following?(user)
    follower_user.include?(user)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	  before_action :authenticate_user!, except: [:top, :about]
	before_action :configure_permitted_parameters, if: :devise_controller?


	def after_sign_in_path_for(resource)
		flash[:notice] = "Signed in successfully."
		user_path(current_user.id)
	end

	def after_sign_out_path_for(resource)
		flash[:notice] = "Signed out successfully."
		root_path
	end
	
  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :email])
  end



end

app/controllers/book_comments_controller.rb
class BookCommentsController < ApplicationController
	def create
    	book = Book.find(params[:book_id])
    	comment = current_user.book_comments.new(book_comment_params)
    	comment.book_id = book.id
    	comment.save
    	redirect_to book_path(book)
	end

	def destroy
		comment = BookComment.find(params[:id])
		book = comment.book
    	comment.destroy
    	redirect_to book_path(book)
	end


	private
	def book_comment_params
   		params.require(:book_comment).permit(:comment)
	end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  def index
    @books = Book.all
    @book = Book.new
  end

  def show
    @book = Book.new
  	@bookf = Book.find(params[:id])
    @book_comment = BookComment.new
  end

  def create
  	@book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
    flash[:notice] = "You have created book successfully."
    redirect_to book_path(@book)
     else
      @books = Book.all
      render :index
    end
  end

  def edit
  	@book =  Book.find(params[:id])
    if @book.user_id != current_user.id
      redirect_to '/books'
    end
  end

  def update
  	@book = Book.find(params[:id])
     @book.user_id = current_user.id
  	if @book.update(book_params)
  	flash[:notice] = "You have updated book successfully."
  	redirect_to book_path(@book.id)
    else
      render :edit
    end
  end

  def destroy
  	book = Book.find(params[:id])
  	book.destroy
  	flash[:notice] = "You have deleted book successfully."
  	redirect_to users_path
  end

  private
    def book_params
      params.require(:book).permit(:title, :body,)
    end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
	def create
			@book = Book.find(params[:book_id])
            favorite = current_user.favorites.new(book_id: @book.id)
            favorite.save
    end

    def destroy
			@book = Book.find(params[:book_id])
            favorite = current_user.favorites.find_by(book_id: @book.id)
            favorite.destroy

    end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	def top
	end

	def about
	end
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
	def follow
		current_user.follow(params[:id])
		redirect_back(fallback_location: root_path)

	end

	def unfollow
		current_user.unfollow(params[:id])
		redirect_back(fallback_location: root_path)

	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

   def following
      @user  = User.find(params[:id])
     @users = @user.following
      render 'relationships/show_following'
  end

    def followers
    @user  = User.find(params[:id])
   @users = @user.follower
    render 'relationships/show_follower'
  end

  def index
    @book = Book.new
    @users = User.all
  end

  def show
    @bookn = Book.new
    @user = User.find(params[:id])
    # @user = current_user
    # @books = Book.all
    @books = @user.books
  end

  def edit
    @user = User.find(params[:id])
    if @user.id != current_user.id
      redirect_to user_path(current_user.id)
    end
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
    flash[:notice] = "You have updated user successfully."
    redirect_to user_path(@user.id)
      else
        render :edit
      end
  end

   def destroy
    @user = User.find(params[:id])
    @user.destroy
    flash[:notice] = "You have deleted user successfully."
    redirect_to users_path
  end


  private
  def user_params
    params.require(:user).permit(:name, :profile_image, :introduction)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/book_comments_helper.rb
module BookCommentsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/users_helper.rb
  
  module UsersHelper
  
end

app/views/books/edit.html.erb
<div class="col-md-6 col-md-offset-3">

<h1>Editing Book</h1>
<div class="error_explanation">
  <% if @book.errors.any? %>
	<h2><%= pluralize(@book.errors.count, "error") %>
          prohibited this book from being saved:
    </h2><br>
    <ul>
	<% @book.errors.full_messages.each do |message| %>
	  <li><%= message %></li>
	<% end %>
    </ul>
  <% end %>
</div>

<%= form_for @book do |f| %>
    <h4>Title</h4>
    <%= f.text_field :title,class: "book_title col-xs-12" %>
    <h4>Body</h4>
    <%= f.text_area :body,class: "book_title col-xs-12" %><br>
    	<%= f.submit 'Update Book', class: "col-xs-12 btn btn-primary" %>
<% end %>

    <%= link_to "Show", book_path(@book.id) %>
    |
    <%= link_to "Back", books_path %>
</div>

app/views/books/index.html.erb
<div class="error_explanation">
  <% if @book.errors.any? %>
    <h2><%= pluralize(@book.errors.count, "error") %>
          prohibited this obj from being saved:
    </h2><br>
      <ul>
        <% @book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
        <% end %>
      </ul>
   <% end %>
</div>

    <div class="col-xs-3">
<%= render "render/uif" , user: current_user, book: @book %>
    </div>

<div class="col-xs-9">
<h2>AllUsersBooks</h2>

<table class="table table-hovor table-inverse">
  <thead>
    <tr>
      <th></th>
      <th>Title</th>
      <th>Opinion</th>
      <th>favo</th>
      <th>comment</th>
    </tr>
  </thead>

  	<% @books.each do |book| %>
    <tbody>
      <tr>
       <td>
        <%= link_to user_path(book.user_id) do %>
        <%= attachment_image_tag book.user, :profile_image, size: "40x40", fallback: "no_image.jpg" %>
        <% end %>
        </td>
       <td><%= link_to book.title, book_path(book.id) %></td>
       <td><%= book.body %></td>
       <td id="favo-<%= book.id %>">
           <%= render 'favorites/favo', book: book %>
       </td>
       <td>コメント数：<%= book.book_comments.count %></td>
      </tr>
  </tbody>
  <% end %>
</table>


    </div>

  

app/views/books/show.html.erb
    <div class="col-xs-3">
<%= render "render/uif" , user:@bookf.user, book:@book %>
    </div>
<div class="col-xs-9">
<h2>Book detail</h2>
<table class="table table-inverse">
 <tbody>
      <tr>
       <td>
        <%= link_to user_path(@bookf.user.id) do %>
          <%= attachment_image_tag @bookf.user, :profile_image, size: "40x40", format: "jpeg", fallback: "no_image.jpg" %><br>
        <% end %>
         <%= link_to @bookf.user.name, user_path(@bookf.user) %>
       </td>
       <td><%= @bookf.title %></td>
       <td><%= @bookf.body %></td>
       <td id="favo-<%= @bookf.id %>">
           <%= render 'favorites/favo', book: @bookf %>
       </td>
       <td>コメント数：<%= @bookf.book_comments.count %></td>

       <% if @bookf.user == current_user %>
       <td ><%= link_to "Edit", edit_book_path(@bookf.id), class: "btn-sm btn-success" %></td>
       <td ><%= link_to "Destroy", book_path(@bookf.id), method: :delete, class: "btn-sm btn-danger", "data-confirm" => "本当に削除しますか？" %></td>
       <% end %>

      </tr>
  </tbody>
</table>
<!-- コメントフォーム
 -->
 <div>
   <%= form_for [@bookf, @book_comment] do |f| %>
            <%= f.text_area :comment, class: "form-control" %>
    <%= f.submit "送信", class: "btn btn-lg btn-base-1 mt-20 pull-right" %>
<% end %>
 </div>

<br><h4>コメント一覧</h4>
 <div>
<% @bookf.book_comments.each do |book_comment| %>
<table>
  <tr>
    <th><%= book_comment.comment %></th>
    <% if book_comment.user == current_user %>
     <th><%= link_to "Destroy", book_comment_path(book_comment), method: :delete, class: "btn-sm btn-danger", "data-confirm" => "本当に削除しますか？" %></th>
     <% end %>
  </tr>
</table>
<% end %>
 </div>

  </div>
   

app/views/favorites/_favo.html.erb
<% if user_signed_in? %>
<% if book.favorited_by?(current_user) %>
    <%= link_to book_favorites_path(book), method: :delete, remote: true do %>
    <i class="fa fa-heart" aria-hidden="true" style="color: red;"></i>
    <%= book.favorites.count %>
    <% end %>
<% else %>
    <%= link_to book_favorites_path(book), method: :post, remote: true do %>
    <i class="fa fa-heart-o" aria-hidden="true"></i>
    <%= book.favorites.count %>
    <% end %>
<% end %>
<% end %>

app/views/favorites/create.js.erb
$('#favo-<%= @book.id %>').html("<%= j(render partial: 'favorites/favo', locals: { book: @book}) %>");

app/views/favorites/destroy.js.erb
$('#favo-<%= @book.id %>').html("<%= j(render partial: 'favorites/favo', locals: { book: @book}) %>");

app/views/home/about.html.erb
<h1>Welcome to<span class="glyphicon glyphicon-book"><strong>Bookers</strong></span> !</h1>

app/views/home/top.html.erb
<div class="container">
		<div class="row">
			<div class="top-message col-md-offset-3 col-md-6">
			<h1>welcome to<span class="glyphicon glyphicon-book"><strong>Bookers</strong> !!</span></h1>
			<p>In <span class="glyphicon glyphicon-book"></span><strong>Bookers</strong>,</p>
			<p>you can share and exchange your opinions , Inpressions , and emotions</p>
			<p>about various books!</p>
			<div class="btn-wrapper">
			<div class="row"><p><%= link_to "Log in", new_user_session_path, class: "sign_in btn btn-info col-xs-10 col-xs-offset-1" %></p></div>
			<div class="row"><p><%= link_to "Sign up", new_user_registration_path, class: "sign_up btn btn-success col-xs-10 col-xs-offset-1" %></p></div>
			</div>
		</div>
	</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css'  %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

      <body>
    <header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <nav class='nav navbar-nav navbar-left' >
      <span class="site-name">Bookers</span>
    </nav>
    <nav>
      <ul class="nav navbar-nav navbar-right">
         <% if user_signed_in? %>
        <li><%= link_to '   Home', user_path(current_user.id), class: "glyphicon glyphicon-home home" %></li>
        <li><%= link_to "   Users", users_path, class: "glyphicon glyphicon-user users" %></li>
         <li><%= link_to "   Books", books_path, class: "glyphicon glyphicon-book books" %></li>
         <li><%= link_to "   logout", destroy_user_session_path, method: :delete, class: "glyphicon glyphicon-log-out logout" %></li>
          <% else%>
          <li><%= link_to "   Home", root_path, class: "glyphicon glyphicon-home home" %></li>
          <li><%= link_to "   About", home_about_path,  class: "glyphicon glyphicon-link about" %></li>
          <li><%= link_to "   sign up", new_user_registration_path, class: "glyphicon glyphicon-edit sign_up" %></li>
          <li><%= link_to "   login", new_user_session_path, class: "glyphicon glyphicon-log-in sign_in" %></li>
          <% end %>
      </ul>
    </nav>
  </div>
</header>


<div class="container">
  <div class="row">
    <% if flash[:notice] %>
      <p class="success-notice"><%= flash[:notice] %></p>
    <% end %>
    <div class="yield">
      <%= yield %>
    </div>
  </div>
</div>
<footer>
  <div class='container'>
    <div class='row'>
      <div class='col-xs-3 col-xs-offset-9'>
        <p>CopyRight Infratop.inc</p>
      </div>
    </div>
  </div>
</footer>

   
  </body>
</html>

app/views/relationships/show_follower.html.erb
<div class="col-xs-10 col-xs-offset-1">
<h2>Follower Users</h2>
	
<table class="table table-inverse">

	<thead>
		<tr>
			<th>image</th>
			<th>name</th>
			<th></th>
		</tr>
	</thead>

	<tbody>
		<% @user.follower_user.where.not(id: current_user.id).each do |user| %>
		<tr>
			<td><%= attachment_image_tag @user_id, :profile_image, size: "40x40",fallback: "no_image.jpg"%></td>
			<td><%= user.name %></td>
			<td>フォロー数：<%= user.following.count %></td>
			<td>フォロワー数：<%= user.follower.count %></td>
			<td>
			 <% unless user == current_user %>
			  <% if current_user.following?(user) %>
		        <%= link_to 'フォロー外す', unfollow_path(user.id), method: :POST %>
		      <% else %>
		        <%= link_to 'フォローする', follow_path(user.id), method: :POST %>
		      <% end %>
		      <% end %>
			</td>
			<td><%= link_to "Show", user_path(user.id) %> </td>
		</tr>
		<% end %>
	</tbody>
</table>
</div>

app/views/relationships/show_following.html.erb
<div class="col-xs-10 col-xs-offset-1">
<h2>Following Users</h2>
	
<table class="table table-inverse">

	<thead>
		<tr>
			<th>image</th>
			<th>name</th>
			<th></th>
		</tr>
	</thead>

	<tbody>
		<% @user.following_user.where.not(id: current_user.id).each do |user| %>
		<tr>
			<td><%= attachment_image_tag @user_id, :profile_image, size: "40x40",fallback: "no_image.jpg"%></td>
			<td><%= user.name %></td>
			<td>フォロー数：<%= user.following.count %></td>
			<td>フォロワー数：<%= user.follower.count %></td>
			<td>
			 <% unless user == current_user %>
			  <% if current_user.following?(user) %>
		        <%= link_to 'フォロー外す', unfollow_path(user.id), method: :POST %>
		      <% else %>
		        <%= link_to 'フォローする', follow_path(user.id), method: :POST %>
		      <% end %>
		      <% end %>
			</td>
			<td><%= link_to "Show", user_path(user.id) %> </td>
		</tr>
		<% end %>
	</tbody>
</table>
</div>


   

app/views/render/_error.html.erb
<% if @book.errors.any? %>
  <h2><%= pluralize(@book.errors.count, "error") %>
          prohibited this book from being saved:
  </h2><br>
  <% @book.errors.full_messages.each do |message| %>
 	<ul>
 		<li><%= message %></li>
 	</ul><br>
  <% end %>
<% end %>

app/views/render/_flash.html.erb
<% if flash[:notice] %>
  <p class="succes-message"><%= flash[:notice] %></p>
<% end %>

app/views/render/_uif.erb
<h2>User info</h2>

<table class="table table-inverse">
    <tr>
       <td><%= attachment_image_tag user, :profile_image, size: "100x100",  format: 'jpeg', fallback: "no_image.jpg"%></td>
    </tr>
    <tr>
      <th>name</th>
      <th><%= user.name %></th>
    </tr>
    <tr>
      <th>introduction</th>
      <th><%= user.introduction %></th>
    </tr>
    <tr>
      <th>follows</th>
      <th>
       <%= link_to user.following.count, following_user_path(user)  %>
        </th>
    </tr>
    <tr>
      <th>follwers</th>
      <th><%= link_to user.follower.count, followers_user_path(user)  %></th>  
    </tr>
    <tr>
      <th>
        <% unless user == current_user %>
        <% if current_user.following?(user) %>
          <%= link_to 'フォロー外す', unfollow_path(user.id), method: :POST %>
        <% else %>
          <%= link_to 'フォローする', follow_path(user.id), method: :POST %>
        <% end %>
        <% end %>
      </th>
    </tr>
</table>
<% if user.id == current_user.id %>
    <%= link_to "", edit_user_path(user), class: "col-xs-12 btn btn-default glyphicon glyphicon-wrench" %>
<% end %>

<h2>New book</h2>
 <%= form_for(book) do |f| %>
    <div class ="field">
    <%= f.label :title %>
    <%= f.text_field :title,class: "col-xs-12" %>
    </div>
    <%= f.label :opinion %>
    <%= f.text_area :body, class: "col-xs-12" %>
       <%= f.submit "Create Book", class: "col-xs-12 btn btn-primary" %>
 <% end %>

app/views/users/edit.html.erb
<dir class="user-edit-form">
<h1>User info</h1>

<%= form_for(@user) do |f| %>
	<div class="error_explanation">
  		<% if @user.errors.any? %>
    		<h2><%= pluralize(@user.errors.count, "error") %>
    		 prohibited this @user from being saved:
    		</h2><br>
     	 <ul>
        <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
        <% end %>
        </ul>
   	  <% end %>
	</div>
	
<%= f.label :name %>
<%= f.text_field :name, autofocus: true %><br>
<%= f.label :image%>
<%= f.attachment_field :profile_image %><br>
<%= f.label :introduction %>
<%= f.text_field :introduction, autofocus: true %><br>


<%= f.submit "Update User" %>

<% end %>


</dir>

app/views/users/index.html.erb
 <div class="container">
  <div class="row">

    <div class="col-xs-3">
<%= render "render/uif", user:current_user, book:@book %>
	</div>

<div class="col-xs-9">
<h2>Users</h2>
	
<table class="table table-inverse">

	<thead>
		<tr>
			<th>image</th>
			<th>name</th>
			<th></th>
		</tr>
	</thead>

	<tbody>
		<% @users.each do |user| %>
		<tr>
			<td><%= attachment_image_tag @user_id, :profile_image, size: "40x40",fallback: "no_image.jpg"%></td>
			<td><%= user.name %></td>
			<td><%= link_to "Show", user_path(user.id) %> </td>
		</tr>
		<% end %>
	</tbody>

</table>


    </div>
   </div>
  </div>

app/views/users/show.html.erb
 
    <div class="col-xs-3">
<%= render "render/uif", user:@user, book:@bookn %>
    </div>
<div class="col-xs-9">

   <h2>here is <%= @user.name %>'s_Books</h2>
<table class="table table-inverse">
  <thead>
    <tr>
      <th></th>
      <th>Title</th>
      <th>Opinion</th>
    </tr>
  </thead>

  	
    <tbody>
     <% @books.each do |book| %>
      <tr>
       <td>
        <%= link_to user_path(@user.id) do %>
          <%= attachment_image_tag @user, :profile_image, size: "40x40",
          fallback: "no_image.jpg"%>
        <% end %>
       </td>
       <td><%= link_to book.title, book_path(book.id) %></td>
       <td><%= book.body %></td>
       <td>コメント数：<%= book.book_comments.count %></td>
       <td><%= link_to "Destroy", user_path(@user.id), method: :delete,
         class: "btn-sm btn-danger", "data-confirm" => "本当に削除しますか？" %> 
       </td>
      </tr>
    <% end %>
  </tbody>
</table>
<td><%= link_to "User Destroy", user_path(@user.id), method: :delete, class: "btn-sm btn-danger", "data-confirm" => "本当に削除しますか？" %></td>
    </div>